# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/ui/mainwindow.ui',
# licensing of 'gui/ui/mainwindow.ui' applies.
#
# Created: Sun May 17 12:55:12 2020
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1289, 913)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.planetConfigButton = QtWidgets.QPushButton(self.centralwidget)
        self.planetConfigButton.setMinimumSize(QtCore.QSize(140, 0))
        self.planetConfigButton.setCursor(QtCore.Qt.PointingHandCursor)
        self.planetConfigButton.setObjectName("planetConfigButton")
        self.horizontalLayout_2.addWidget(self.planetConfigButton)
        self.themeButton = QtWidgets.QPushButton(self.centralwidget)
        self.themeButton.setObjectName("themeButton")
        self.horizontalLayout_2.addWidget(self.themeButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.techID = QtWidgets.QLineEdit(self.centralwidget)
        self.techID.setMinimumSize(QtCore.QSize(150, 0))
        self.techID.setObjectName("techID")
        self.horizontalLayout_2.addWidget(self.techID)
        self.techIDbutton = QtWidgets.QPushButton(self.centralwidget)
        self.techIDbutton.setMinimumSize(QtCore.QSize(24, 24))
        self.techIDbutton.setMaximumSize(QtCore.QSize(24, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.techIDbutton.setFont(font)
        self.techIDbutton.setIconSize(QtCore.QSize(22, 22))
        self.techIDbutton.setCheckable(True)
        self.techIDbutton.setObjectName("techIDbutton")
        self.horizontalLayout_2.addWidget(self.techIDbutton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.randomButton = QtWidgets.QPushButton(self.centralwidget)
        self.randomButton.setCursor(QtCore.Qt.PointingHandCursor)
        self.randomButton.setObjectName("randomButton")
        self.horizontalLayout_2.addWidget(self.randomButton)
        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout_2.addWidget(self.clearButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(1265, 455))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setObjectName("tabWidget")
        self.machine1 = QtWidgets.QWidget()
        self.machine1.setObjectName("machine1")
        self.layoutWidget = QtWidgets.QWidget(self.machine1)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 110, 1241, 307))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.planet1Box = QtWidgets.QGroupBox(self.layoutWidget)
        self.planet1Box.setMinimumSize(QtCore.QSize(235, 305))
        self.planet1Box.setCursor(QtCore.Qt.ArrowCursor)
        self.planet1Box.setObjectName("planet1Box")
        self.pie1Container = QtWidgets.QWidget(self.planet1Box)
        self.pie1Container.setGeometry(QtCore.QRect(2, 75, 239, 239))
        self.pie1Container.setObjectName("pie1Container")
        self.infoP1 = QtWidgets.QLabel(self.planet1Box)
        self.infoP1.setGeometry(QtCore.QRect(0, 20, 243, 49))
        self.infoP1.setMinimumSize(QtCore.QSize(243, 45))
        self.infoP1.setMaximumSize(QtCore.QSize(180, 60))
        self.infoP1.setAlignment(QtCore.Qt.AlignCenter)
        self.infoP1.setObjectName("infoP1")
        self.horizontalLayout_8.addWidget(self.planet1Box)
        self.planet2Box = QtWidgets.QGroupBox(self.layoutWidget)
        self.planet2Box.setMinimumSize(QtCore.QSize(235, 290))
        self.planet2Box.setObjectName("planet2Box")
        self.pie2Container = QtWidgets.QWidget(self.planet2Box)
        self.pie2Container.setGeometry(QtCore.QRect(2, 75, 239, 239))
        self.pie2Container.setObjectName("pie2Container")
        self.infoP2 = QtWidgets.QLabel(self.planet2Box)
        self.infoP2.setGeometry(QtCore.QRect(0, 20, 243, 49))
        self.infoP2.setMinimumSize(QtCore.QSize(0, 45))
        self.infoP2.setMaximumSize(QtCore.QSize(16777215, 60))
        self.infoP2.setAlignment(QtCore.Qt.AlignCenter)
        self.infoP2.setObjectName("infoP2")
        self.horizontalLayout_8.addWidget(self.planet2Box)
        self.planet3Box = QtWidgets.QGroupBox(self.layoutWidget)
        self.planet3Box.setMinimumSize(QtCore.QSize(235, 270))
        self.planet3Box.setObjectName("planet3Box")
        self.pie3Container = QtWidgets.QWidget(self.planet3Box)
        self.pie3Container.setGeometry(QtCore.QRect(2, 75, 239, 239))
        self.pie3Container.setObjectName("pie3Container")
        self.infoP3 = QtWidgets.QLabel(self.planet3Box)
        self.infoP3.setGeometry(QtCore.QRect(0, 20, 243, 49))
        self.infoP3.setMinimumSize(QtCore.QSize(0, 45))
        self.infoP3.setMaximumSize(QtCore.QSize(16777215, 60))
        self.infoP3.setAlignment(QtCore.Qt.AlignCenter)
        self.infoP3.setObjectName("infoP3")
        self.horizontalLayout_8.addWidget(self.planet3Box)
        self.planet4Box = QtWidgets.QGroupBox(self.layoutWidget)
        self.planet4Box.setMinimumSize(QtCore.QSize(235, 270))
        self.planet4Box.setObjectName("planet4Box")
        self.pie4Container = QtWidgets.QWidget(self.planet4Box)
        self.pie4Container.setGeometry(QtCore.QRect(2, 75, 239, 239))
        self.pie4Container.setObjectName("pie4Container")
        self.infoP4 = QtWidgets.QLabel(self.planet4Box)
        self.infoP4.setGeometry(QtCore.QRect(0, 20, 243, 49))
        self.infoP4.setMinimumSize(QtCore.QSize(0, 45))
        self.infoP4.setMaximumSize(QtCore.QSize(16777215, 60))
        self.infoP4.setAlignment(QtCore.Qt.AlignCenter)
        self.infoP4.setObjectName("infoP4")
        self.horizontalLayout_8.addWidget(self.planet4Box)
        self.planet5Box = QtWidgets.QGroupBox(self.layoutWidget)
        self.planet5Box.setMinimumSize(QtCore.QSize(235, 270))
        self.planet5Box.setObjectName("planet5Box")
        self.pie5Container = QtWidgets.QWidget(self.planet5Box)
        self.pie5Container.setGeometry(QtCore.QRect(2, 75, 239, 239))
        self.pie5Container.setObjectName("pie5Container")
        self.infoP5 = QtWidgets.QLabel(self.planet5Box)
        self.infoP5.setGeometry(QtCore.QRect(0, 20, 243, 49))
        self.infoP5.setMinimumSize(QtCore.QSize(0, 45))
        self.infoP5.setMaximumSize(QtCore.QSize(16777215, 60))
        self.infoP5.setAlignment(QtCore.Qt.AlignCenter)
        self.infoP5.setObjectName("infoP5")
        self.horizontalLayout_8.addWidget(self.planet5Box)
        self.line = QtWidgets.QFrame(self.machine1)
        self.line.setGeometry(QtCore.QRect(10, 90, 1241, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.layoutWidget1 = QtWidgets.QWidget(self.machine1)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 1244, 81))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_38 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_38.setMaximumSize(QtCore.QSize(65, 35))
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_5.addWidget(self.label_38)
        self.startTime = QtWidgets.QTimeEdit(self.layoutWidget1)
        self.startTime.setAutoFillBackground(True)
        self.startTime.setObjectName("startTime")
        self.horizontalLayout_5.addWidget(self.startTime)
        self.stButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.stButton.setMinimumSize(QtCore.QSize(28, 28))
        self.stButton.setMaximumSize(QtCore.QSize(28, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.stButton.setFont(font)
        self.stButton.setIconSize(QtCore.QSize(22, 22))
        self.stButton.setCheckable(True)
        self.stButton.setObjectName("stButton")
        self.horizontalLayout_5.addWidget(self.stButton)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_5)
        spacerItem6 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_39 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_39.setMaximumSize(QtCore.QSize(65, 35))
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_7.addWidget(self.label_39)
        self.loadTime = QtWidgets.QTimeEdit(self.layoutWidget1)
        self.loadTime.setObjectName("loadTime")
        self.horizontalLayout_7.addWidget(self.loadTime)
        self.ltButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.ltButton.setMinimumSize(QtCore.QSize(28, 28))
        self.ltButton.setMaximumSize(QtCore.QSize(28, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ltButton.setFont(font)
        self.ltButton.setIconSize(QtCore.QSize(22, 22))
        self.ltButton.setCheckable(True)
        self.ltButton.setObjectName("ltButton")
        self.horizontalLayout_7.addWidget(self.ltButton)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_53 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_53.setMinimumSize(QtCore.QSize(65, 0))
        self.label_53.setMaximumSize(QtCore.QSize(65, 35))
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_29.addWidget(self.label_53)
        self.endTime = QtWidgets.QTimeEdit(self.layoutWidget1)
        self.endTime.setObjectName("endTime")
        self.horizontalLayout_29.addWidget(self.endTime)
        self.etButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.etButton.setMinimumSize(QtCore.QSize(28, 28))
        self.etButton.setMaximumSize(QtCore.QSize(28, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.etButton.setFont(font)
        self.etButton.setIconSize(QtCore.QSize(22, 22))
        self.etButton.setCheckable(True)
        self.etButton.setObjectName("etButton")
        self.horizontalLayout_29.addWidget(self.etButton)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_29)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_34 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_34.setMaximumSize(QtCore.QSize(77, 35))
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_20.addWidget(self.label_34)
        self.unloadTime = QtWidgets.QTimeEdit(self.layoutWidget1)
        self.unloadTime.setObjectName("unloadTime")
        self.horizontalLayout_20.addWidget(self.unloadTime)
        self.utButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.utButton.setMinimumSize(QtCore.QSize(28, 28))
        self.utButton.setMaximumSize(QtCore.QSize(28, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.utButton.setFont(font)
        self.utButton.setIconSize(QtCore.QSize(22, 22))
        self.utButton.setCheckable(True)
        self.utButton.setObjectName("utButton")
        self.horizontalLayout_20.addWidget(self.utButton)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_20)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_18.addLayout(self.verticalLayout_3)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem8)
        spacerItem9 = QtWidgets.QSpacerItem(13, 107, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem9)
        self.addWorkOrderButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.addWorkOrderButton.setMinimumSize(QtCore.QSize(210, 60))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.addWorkOrderButton.setFont(font)
        self.addWorkOrderButton.setCursor(QtCore.Qt.PointingHandCursor)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Custom-Icon-Design-Flatastic-1-Add-1.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addWorkOrderButton.setIcon(icon)
        self.addWorkOrderButton.setObjectName("addWorkOrderButton")
        self.horizontalLayout_18.addWidget(self.addWorkOrderButton)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem10)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_18)
        spacerItem11 = QtWidgets.QSpacerItem(13, 107, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem11)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem12)
        self.label_40 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_40.setMaximumSize(QtCore.QSize(44, 35))
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_12.addWidget(self.label_40)
        self.cdn = QtWidgets.QLineEdit(self.layoutWidget1)
        self.cdn.setMinimumSize(QtCore.QSize(62, 0))
        self.cdn.setMaximumSize(QtCore.QSize(62, 16777215))
        self.cdn.setAlignment(QtCore.Qt.AlignCenter)
        self.cdn.setObjectName("cdn")
        self.horizontalLayout_12.addWidget(self.cdn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_35 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_35.setMaximumSize(QtCore.QSize(110, 35))
        self.label_35.setObjectName("label_35")
        self.horizontalLayout.addWidget(self.label_35)
        self.loadingRun = QtWidgets.QLineEdit(self.layoutWidget1)
        self.loadingRun.setMinimumSize(QtCore.QSize(62, 0))
        self.loadingRun.setMaximumSize(QtCore.QSize(56, 16777215))
        self.loadingRun.setAlignment(QtCore.Qt.AlignCenter)
        self.loadingRun.setObjectName("loadingRun")
        self.horizontalLayout.addWidget(self.loadingRun)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_17.addLayout(self.verticalLayout_4)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem13)
        self.label_41 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_41.setMaximumSize(QtCore.QSize(89, 35))
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_15.addWidget(self.label_41)
        self.testRun = QtWidgets.QLineEdit(self.layoutWidget1)
        self.testRun.setMinimumSize(QtCore.QSize(62, 0))
        self.testRun.setMaximumSize(QtCore.QSize(62, 16777215))
        self.testRun.setAlignment(QtCore.Qt.AlignCenter)
        self.testRun.setObjectName("testRun")
        self.horizontalLayout_15.addWidget(self.testRun)
        self.verticalLayout_6.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem14)
        self.label_36 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_36.setMaximumSize(QtCore.QSize(126, 35))
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_13.addWidget(self.label_36)
        self.setupTestRun = QtWidgets.QLineEdit(self.layoutWidget1)
        self.setupTestRun.setMinimumSize(QtCore.QSize(62, 0))
        self.setupTestRun.setMaximumSize(QtCore.QSize(56, 16777215))
        self.setupTestRun.setAlignment(QtCore.Qt.AlignCenter)
        self.setupTestRun.setObjectName("setupTestRun")
        self.horizontalLayout_13.addWidget(self.setupTestRun)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_17.addLayout(self.verticalLayout_6)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem15)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_37 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_37.setMaximumSize(QtCore.QSize(145, 35))
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_16.addWidget(self.label_37)
        self.coatRun = QtWidgets.QLineEdit(self.layoutWidget1)
        self.coatRun.setMinimumSize(QtCore.QSize(62, 0))
        self.coatRun.setMaximumSize(QtCore.QSize(56, 16777215))
        self.coatRun.setAlignment(QtCore.Qt.AlignCenter)
        self.coatRun.setObjectName("coatRun")
        self.horizontalLayout_16.addWidget(self.coatRun)
        self.verticalLayout_8.addLayout(self.horizontalLayout_16)
        self.validateButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.validateButton.setMinimumSize(QtCore.QSize(160, 35))
        self.validateButton.setCursor(QtCore.Qt.PointingHandCursor)
        self.validateButton.setCheckable(True)
        self.validateButton.setObjectName("validateButton")
        self.verticalLayout_8.addWidget(self.validateButton)
        self.horizontalLayout_17.addLayout(self.verticalLayout_8)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_17)
        self.tabWidget.addTab(self.machine1, "")
        self.machine2 = QtWidgets.QWidget()
        self.machine2.setObjectName("machine2")
        self.tabWidget.addTab(self.machine2, "")
        self.machine3 = QtWidgets.QWidget()
        self.machine3.setObjectName("machine3")
        self.tabWidget.addTab(self.machine3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 14))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.resultsContainer = QtWidgets.QWidget(self.centralwidget)
        self.resultsContainer.setMinimumSize(QtCore.QSize(1265, 321))
        self.resultsContainer.setObjectName("resultsContainer")
        self.verticalLayout.addWidget(self.resultsContainer)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_7.addLayout(self.verticalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1289, 26))
        self.menubar.setObjectName("menubar")
        self.menuWorkOrder_Tracker = QtWidgets.QMenu(self.menubar)
        self.menuWorkOrder_Tracker.setObjectName("menuWorkOrder_Tracker")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setEnabled(False)
        self.actionSave.setObjectName("actionSave")
        self.actionStart_Time = QtWidgets.QAction(MainWindow)
        self.actionStart_Time.setObjectName("actionStart_Time")
        self.actionExport_As = QtWidgets.QAction(MainWindow)
        self.actionExport_As.setObjectName("actionExport_As")
        self.actionEnable_Auto_Show = QtWidgets.QAction(MainWindow)
        self.actionEnable_Auto_Show.setCheckable(True)
        self.actionEnable_Auto_Show.setChecked(True)
        self.actionEnable_Auto_Show.setObjectName("actionEnable_Auto_Show")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.menuWorkOrder_Tracker.addAction(self.actionSave)
        self.menuWorkOrder_Tracker.addAction(self.actionLoad)
        self.menubar.addAction(self.menuWorkOrder_Tracker.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.planetConfigButton.setText(QtWidgets.QApplication.translate("MainWindow", "Planet Configuration", None, -1))
        self.themeButton.setText(QtWidgets.QApplication.translate("MainWindow", "Light Mode", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Technician ID:", None, -1))
        self.techID.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "12345678", None, -1))
        self.techIDbutton.setText(QtWidgets.QApplication.translate("MainWindow", "✓", None, -1))
        self.randomButton.setText(QtWidgets.QApplication.translate("MainWindow", "Demo", None, -1))
        self.clearButton.setText(QtWidgets.QApplication.translate("MainWindow", "Clear", None, -1))
        self.planet1Box.setTitle(QtWidgets.QApplication.translate("MainWindow", "  Planet 1", None, -1))
        self.infoP1.setText(QtWidgets.QApplication.translate("MainWindow", "Work Order Info P1", None, -1))
        self.planet2Box.setTitle(QtWidgets.QApplication.translate("MainWindow", "  Planet 2", None, -1))
        self.infoP2.setText(QtWidgets.QApplication.translate("MainWindow", "Work Order Info P1", None, -1))
        self.planet3Box.setTitle(QtWidgets.QApplication.translate("MainWindow", "  Planet 3", None, -1))
        self.infoP3.setText(QtWidgets.QApplication.translate("MainWindow", "Work Order Info P1", None, -1))
        self.planet4Box.setTitle(QtWidgets.QApplication.translate("MainWindow", "  Planet 4", None, -1))
        self.infoP4.setText(QtWidgets.QApplication.translate("MainWindow", "Work Order Info P1", None, -1))
        self.planet5Box.setTitle(QtWidgets.QApplication.translate("MainWindow", "  Planet 5", None, -1))
        self.infoP5.setText(QtWidgets.QApplication.translate("MainWindow", "Work Order Info P1", None, -1))
        self.label_38.setText(QtWidgets.QApplication.translate("MainWindow", "Start Time:", None, -1))
        self.stButton.setText(QtWidgets.QApplication.translate("MainWindow", "✓", None, -1))
        self.label_39.setText(QtWidgets.QApplication.translate("MainWindow", "Load Time:", None, -1))
        self.ltButton.setText(QtWidgets.QApplication.translate("MainWindow", "✓", None, -1))
        self.label_53.setText(QtWidgets.QApplication.translate("MainWindow", " End Time:", None, -1))
        self.etButton.setText(QtWidgets.QApplication.translate("MainWindow", "✓", None, -1))
        self.label_34.setText(QtWidgets.QApplication.translate("MainWindow", "Unload Time:", None, -1))
        self.utButton.setText(QtWidgets.QApplication.translate("MainWindow", "✓", None, -1))
        self.addWorkOrderButton.setText(QtWidgets.QApplication.translate("MainWindow", "➕  Add Work Order", None, -1))
        self.label_40.setText(QtWidgets.QApplication.translate("MainWindow", "CDN #:", None, -1))
        self.label_35.setText(QtWidgets.QApplication.translate("MainWindow", "Loading Run (Hrs):", None, -1))
        self.label_41.setText(QtWidgets.QApplication.translate("MainWindow", "Test Run (Hrs):", None, -1))
        self.label_36.setText(QtWidgets.QApplication.translate("MainWindow", "Setup Test Run (Hrs):", None, -1))
        self.label_37.setText(QtWidgets.QApplication.translate("MainWindow", "Coating Run (Hrs):", None, -1))
        self.validateButton.setText(QtWidgets.QApplication.translate("MainWindow", "Lock", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.machine1), QtWidgets.QApplication.translate("MainWindow", "Machine 1", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.machine2), QtWidgets.QApplication.translate("MainWindow", "Machine 2", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.machine3), QtWidgets.QApplication.translate("MainWindow", "Machine 3", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "  Results", None, -1))
        self.menuWorkOrder_Tracker.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.actionSave.setText(QtWidgets.QApplication.translate("MainWindow", "Save As...", None, -1))
        self.actionStart_Time.setText(QtWidgets.QApplication.translate("MainWindow", "Start Time", None, -1))
        self.actionExport_As.setText(QtWidgets.QApplication.translate("MainWindow", "Export As...", None, -1))
        self.actionEnable_Auto_Show.setText(QtWidgets.QApplication.translate("MainWindow", "Enable Auto-Show", None, -1))
        self.actionLoad.setText(QtWidgets.QApplication.translate("MainWindow", "Load File...", None, -1))

