# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/ui/planetConfigDialog.ui',
# licensing of 'gui/ui/planetConfigDialog.ui' applies.
#
# Created: Sun May 17 12:55:13 2020
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(667, 413)
        Dialog.setMinimumSize(QtCore.QSize(667, 413))
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(310, 370, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 641, 351))
        self.tabWidget.setObjectName("tabWidget")
        self.machine1 = QtWidgets.QWidget()
        self.machine1.setObjectName("machine1")
        self.widget = QtWidgets.QWidget(self.machine1)
        self.widget.setGeometry(QtCore.QRect(0, 0, 631, 321))
        self.widget.setObjectName("widget")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem9)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem10)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_11.addLayout(self.verticalLayout)
        spacerItem11 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem11)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.planet1Num = QtWidgets.QSpinBox(self.widget)
        self.planet1Num.setEnabled(True)
        self.planet1Num.setMinimumSize(QtCore.QSize(220, 0))
        self.planet1Num.setReadOnly(True)
        self.planet1Num.setObjectName("planet1Num")
        self.horizontalLayout_10.addWidget(self.planet1Num)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_10.addWidget(self.label_6)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem12)
        self.planet1Enable = QtWidgets.QPushButton(self.widget)
        self.planet1Enable.setCheckable(True)
        self.planet1Enable.setObjectName("planet1Enable")
        self.horizontalLayout_10.addWidget(self.planet1Enable)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem13)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.planet2Num = QtWidgets.QSpinBox(self.widget)
        self.planet2Num.setEnabled(True)
        self.planet2Num.setMinimumSize(QtCore.QSize(220, 0))
        self.planet2Num.setReadOnly(True)
        self.planet2Num.setObjectName("planet2Num")
        self.horizontalLayout_9.addWidget(self.planet2Num)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem14)
        self.planet2Enable = QtWidgets.QPushButton(self.widget)
        self.planet2Enable.setCheckable(True)
        self.planet2Enable.setObjectName("planet2Enable")
        self.horizontalLayout_9.addWidget(self.planet2Enable)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem15)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.planet3Num = QtWidgets.QSpinBox(self.widget)
        self.planet3Num.setEnabled(True)
        self.planet3Num.setMinimumSize(QtCore.QSize(220, 0))
        self.planet3Num.setReadOnly(True)
        self.planet3Num.setObjectName("planet3Num")
        self.horizontalLayout_8.addWidget(self.planet3Num)
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem16)
        self.planet3Enable = QtWidgets.QPushButton(self.widget)
        self.planet3Enable.setCheckable(True)
        self.planet3Enable.setObjectName("planet3Enable")
        self.horizontalLayout_8.addWidget(self.planet3Enable)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem17)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.planet4Num = QtWidgets.QSpinBox(self.widget)
        self.planet4Num.setEnabled(True)
        self.planet4Num.setMinimumSize(QtCore.QSize(220, 0))
        self.planet4Num.setReadOnly(True)
        self.planet4Num.setObjectName("planet4Num")
        self.horizontalLayout_7.addWidget(self.planet4Num)
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem18)
        self.planet4Enable = QtWidgets.QPushButton(self.widget)
        self.planet4Enable.setCheckable(True)
        self.planet4Enable.setObjectName("planet4Enable")
        self.horizontalLayout_7.addWidget(self.planet4Enable)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem19)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.planet5Num = QtWidgets.QSpinBox(self.widget)
        self.planet5Num.setEnabled(True)
        self.planet5Num.setMinimumSize(QtCore.QSize(220, 0))
        self.planet5Num.setReadOnly(True)
        self.planet5Num.setObjectName("planet5Num")
        self.horizontalLayout_6.addWidget(self.planet5Num)
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_6.addWidget(self.label_10)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem20)
        self.planet5Enable = QtWidgets.QPushButton(self.widget)
        self.planet5Enable.setCheckable(True)
        self.planet5Enable.setObjectName("planet5Enable")
        self.horizontalLayout_6.addWidget(self.planet5Enable)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_11.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        spacerItem21 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem21)
        self.horizontalLayout_12.addLayout(self.verticalLayout_3)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem22)
        self.tabWidget.addTab(self.machine1, "")
        self.machine2 = QtWidgets.QWidget()
        self.machine2.setObjectName("machine2")
        self.tabWidget.addTab(self.machine2, "")
        self.machine3 = QtWidgets.QWidget()
        self.machine3.setAccessibleName("")
        self.machine3.setObjectName("machine3")
        self.tabWidget.addTab(self.machine3, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "Dialog", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Dialog", "Planet 1:", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Dialog", "Planet 2:", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Dialog", "Planet 3:", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Dialog", "Planet 4:", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Dialog", "Planet 5:", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Dialog", "pieces", None, -1))
        self.planet1Enable.setText(QtWidgets.QApplication.translate("Dialog", "Enable", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("Dialog", "pieces", None, -1))
        self.planet2Enable.setText(QtWidgets.QApplication.translate("Dialog", "Enable", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("Dialog", "pieces", None, -1))
        self.planet3Enable.setText(QtWidgets.QApplication.translate("Dialog", "Enable", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("Dialog", "pieces", None, -1))
        self.planet4Enable.setText(QtWidgets.QApplication.translate("Dialog", "Enable", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("Dialog", "pieces", None, -1))
        self.planet5Enable.setText(QtWidgets.QApplication.translate("Dialog", "Enable", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.machine1), QtWidgets.QApplication.translate("Dialog", "Machine 1", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.machine2), QtWidgets.QApplication.translate("Dialog", "Machine 2", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.machine3), QtWidgets.QApplication.translate("Dialog", "Machine 3", None, -1))

